# Makefile generated by hand.
CC = gcc
CFLAGS = -O3
LIBS = -lgmp -lm

OBJEXT = o

all: pi gmp-chudnovsky.$(OBJEXT)

pi: gmp-chudnovsky.$(OBJEXT)
	$(CC) $(LDFLAGS) $^ $(LIBS) -o $@

%.$(OBJEXT): %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	$(RM) *.o pi

.PHONY: all clean
